"""
visualization.py
------------------
Generates the figures required for the Role 2 report/paper:

  Figure 1 - Location distribution
  Figure 3 - Teacher qualification histogram
  Figure 4 - Real vs. Synthetic comparison (all variables, side by side)
  Figure 5 (optional) - Quality score comparison, CTGAN vs Gaussian Copula

NOTE: Figure 2 (the fusion flowchart) is NOT generated by this script.
That one is a process diagram, not a data plot -- build it separately
in draw.io or Mermaid (see the roadmap doc for the exact box/arrow spec).

Run:
    python src/visualization.py
Requires:
    data/seed/seed_dataset.csv
    data/synthetic/gaussian_dataset.csv  (or your selected final model)
    data/reports/sdmetrics_report.json
Output:
    figures/figure1_location_distribution.png
    figures/figure3_teacher_qualification_histogram.png
    figures/figure4_real_vs_synthetic_comparison.png
    figures/figure5_quality_score_comparison.png
"""

import json
import pandas as pd
import matplotlib.pyplot as plt

SEED_PATH = "data/seed/seed_dataset.csv"
FINAL_SYNTHETIC_PATH = "data/synthetic/gaussian_dataset.csv"
SDMETRICS_REPORT_PATH = "data/reports/sdmetrics_report.json"
FIGURES_DIR = "figures"

plt.rcParams["figure.dpi"] = 150
plt.rcParams["savefig.dpi"] = 300


def figure1_location_distribution(real_df):
    fig, ax = plt.subplots(figsize=(6, 4))
    real_df["location"].value_counts(normalize=True).sort_index().plot(
        kind="bar", ax=ax, color="#4C72B0"
    )
    ax.set_title("Figure 1: School Location Distribution")
    ax.set_xlabel("Location")
    ax.set_ylabel("Proportion")
    ax.set_xticklabels(ax.get_xticklabels(), rotation=0)
    plt.tight_layout()
    plt.savefig(f"{FIGURES_DIR}/figure1_location_distribution.png")
    plt.close()


def figure3_teacher_qualification_histogram(real_df):
    fig, ax = plt.subplots(figsize=(6, 4))
    order = ["untrained", "diploma", "degree", "postgraduate"]
    counts = real_df["teacher_qualification"].value_counts().reindex(order)
    counts.plot(kind="bar", ax=ax, color="#DD8452")
    ax.set_title("Figure 3: Teacher Qualification Distribution")
    ax.set_xlabel("Qualification")
    ax.set_ylabel("Count")
    ax.set_xticklabels(ax.get_xticklabels(), rotation=30, ha="right")
    plt.tight_layout()
    plt.savefig(f"{FIGURES_DIR}/figure3_teacher_qualification_histogram.png")
    plt.close()


def figure4_real_vs_synthetic(real_df, synth_df):
    cols = ["location", "tablet_access", "bandwidth", "resource_level", "teacher_qualification"]
    fig, axes = plt.subplots(2, 3, figsize=(15, 8))
    axes = axes.flatten()

    for i, col in enumerate(cols):
        ax = axes[i]
        real_props = real_df[col].value_counts(normalize=True).sort_index()
        synth_props = synth_df[col].value_counts(normalize=True).sort_index()

        # align categories
        categories = sorted(set(real_props.index) | set(synth_props.index))
        real_props = real_props.reindex(categories, fill_value=0)
        synth_props = synth_props.reindex(categories, fill_value=0)

        x = range(len(categories))
        width = 0.35
        ax.bar([p - width/2 for p in x], real_props.values, width, label="Real (seed)", color="#4C72B0")
        ax.bar([p + width/2 for p in x], synth_props.values, width, label="Synthetic", color="#DD8452")
        ax.set_xticks(list(x))
        ax.set_xticklabels(categories, rotation=30, ha="right", fontsize=8)
        ax.set_title(col, fontsize=10)
        ax.legend(fontsize=7)

    axes[-1].axis("off")  # unused 6th subplot
    fig.suptitle("Figure 4: Real vs. Synthetic Distribution Comparison", fontsize=13)
    plt.tight_layout()
    plt.savefig(f"{FIGURES_DIR}/figure4_real_vs_synthetic_comparison.png")
    plt.close()


def figure5_quality_score_comparison():
    with open(SDMETRICS_REPORT_PATH) as f:
        report = json.load(f)

    models = [r["model"] for r in report["results"]]
    scores = [r["overall_quality_score"] for r in report["results"]]

    fig, ax = plt.subplots(figsize=(5, 4))
    bars = ax.bar(models, scores, color=["#C44E52", "#55A868"])
    ax.set_ylim(0, 1)
    ax.set_ylabel("Overall SDMetrics Quality Score")
    ax.set_title("Figure 5: Quality Score Comparison")
    for bar, score in zip(bars, scores):
        ax.text(bar.get_x() + bar.get_width()/2, score + 0.02, f"{score:.4f}",
                ha="center", fontsize=10)
    plt.tight_layout()
    plt.savefig(f"{FIGURES_DIR}/figure5_quality_score_comparison.png")
    plt.close()


if __name__ == "__main__":
    real_df = pd.read_csv(SEED_PATH)
    synth_df = pd.read_csv(FINAL_SYNTHETIC_PATH)

    figure1_location_distribution(real_df)
    print("Saved: figures/figure1_location_distribution.png")

    figure3_teacher_qualification_histogram(real_df)
    print("Saved: figures/figure3_teacher_qualification_histogram.png")

    figure4_real_vs_synthetic(real_df, synth_df)
    print("Saved: figures/figure4_real_vs_synthetic_comparison.png")

    figure5_quality_score_comparison()
    print("Saved: figures/figure5_quality_score_comparison.png")

    print("\nDone. Remember: Figure 2 (fusion flowchart) is built separately in draw.io/Mermaid.")
